/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lduboeuf.example.observerpattern;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lionel
 */
public class FormationForm extends javax.swing.JDialog {

    //ici on stocke les écouteurs aux évènements
    List<FormationEventListener> listeners = new ArrayList<>();
    
    
    //on déclare la liste des évènements dans une interface ( peut être dans une classe externe)
    public interface FormationEventListener {
        public void onCreatedFormation(Formation newForm);
        public void onUpdatedFormation(Formation updatedForm);
    }
    
    /**
     * Creates new form FormationForm
     */
    public FormationForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    
    /**
     * abonnement aux évènements de ce composant
     * @param listener 
     */
    public void addEventListener(FormationEventListener listener){
        this.listeners.add(listener);
    }
    
    /**
     * on notify les écouteurs de l'évènement d'une nouvelle formation
     * @param newForm 
     */
    private void fireCreateFormation(Formation newForm){
        for (FormationEventListener listener: this.listeners){
            listener.onCreatedFormation(newForm);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFormName = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtFormName.setText("nom");
        txtFormName.setToolTipText("");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtFormName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFormName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        
        Logger.getLogger(FormationForm.class.getName()).log(Level.INFO, txtFormName.getText());
        Formation newForm = new Formation(txtFormName.getText());
        //on emet l'evenement de nouvelle formation aux écouteurs
        fireCreateFormation(newForm);
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JTextField txtFormName;
    // End of variables declaration//GEN-END:variables
}
